
project_id = "zqlckixwpyrwdwrsuhsg"

[functions.admin-role]

[functions.create-system-stats]
verify_jwt = false

[functions.update-system-stats]
verify_jwt = false

[functions.get-service-key]

[functions.manage-user]

