
zqlckixwpyrwdwrsuhsg

[functions."get-service-key"]
verify_jwt = true

[functions."manage-user"]
verify_jwt = true

[functions."create-system-stats"]
verify_jwt = true

[functions."update-system-stats"]
verify_jwt = true

[functions."check-notifications-table"]
verify_jwt = true

[functions."handle-password-reset"]
verify_jwt = false

[functions."setup-notifications-rpcs"]
verify_jwt = true
