project_id = "zqlckixwpyrwdwrsuhsg"

[functions."store-api"]
verify_jwt = false

[functions."get-service-key"]
verify_jwt = true

[functions."manage-user"]
verify_jwt = true

[functions."create-system-stats"]
verify_jwt = true

[functions."update-system-stats"]
verify_jwt = true

[functions."check-notifications-table"]
verify_jwt = true

[functions."handle-password-reset"]
verify_jwt = false

[functions."setup-notifications-rpcs"]
verify_jwt = true

[functions."cleanup-feedback"]
verify_jwt = false

[functions."send-whatsapp-notification"]
verify_jwt = false

[functions."calculate-daily-sales"]
verify_jwt = false

[functions."ai-product-assistant"]
verify_jwt = true

[functions."customer-ai-assistant"]
verify_jwt = false

[functions."whatsapp-bot"]
verify_jwt = false

[functions."cleanup-orphaned-files"]
verify_jwt = true

[functions."cloudinary-optimize"]
verify_jwt = false
