
project_id = "zqlckixwpyrwdwrsuhsg"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[functions]
[functions.manage-user]
verify_jwt = false

[functions.get-service-key]
verify_jwt = false

[functions.admin-role]
verify_jwt = false

[functions.create-system-stats]
verify_jwt = false

[functions.update-system-stats]
verify_jwt = false

[functions.handle-password-reset]
verify_jwt = false
