import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { categoryName, userId, iconStyle } = await req.json();
    console.log(`Generating icon for: "${categoryName}", style: ${iconStyle || "flat"}, user: ${userId}`);

    if (!categoryName || !userId) {
      return new Response(
        JSON.stringify({ error: "categoryName and userId are required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      return new Response(
        JSON.stringify({ error: "LOVABLE_API_KEY is not configured" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const stylePrompts: Record<string, string> = {
      flat: "flat design, bold solid colors, clean geometric shapes, minimal modern style",
      "3d": "glossy 3D rendered, realistic lighting, soft shadows, shiny surface",
      cartoon: "cartoon-style, thick black outlines, bright saturated colors, cute and playful",
    };

    const styleDesc = stylePrompts[iconStyle || "flat"] || stylePrompts.flat;

    // Use a very specific, direct prompt - request JPEG-friendly (opaque) output
    const prompt = `Generate a single icon for the restaurant menu category "${categoryName}".

Style: ${styleDesc}

CRITICAL REQUIREMENTS:
- Draw a large, colorful food/drink illustration representing "${categoryName}"
- Use a SOLID BRIGHT colored background (like orange, blue, green, or yellow - NOT white, NOT transparent, NOT gray)
- The illustration must be centered and fill 70% of the image
- Use rich, vibrant, saturated colors
- NO text, NO words, NO letters, NO numbers anywhere
- Make the background a solid bright color, never white or transparent`;

    const model = "google/gemini-2.5-flash-image";
    console.log(`Sending prompt to AI with model ${model}...`);

    const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model,
        messages: [
          { 
            role: "user", 
            content: prompt 
          }
        ],
        modalities: ["image", "text"],
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error(`AI gateway error ${aiResponse.status}:`, errorText);
      return new Response(
        JSON.stringify({ error: `AI error: ${aiResponse.status}` }),
        { status: aiResponse.status, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const aiData = await aiResponse.json();
    console.log("AI response received, checking for images...");
    
    // Log the full response structure for debugging
    const msg = aiData.choices?.[0]?.message;
    console.log(`Response has content: ${!!msg?.content}, images count: ${msg?.images?.length || 0}`);
    
    const imageData = msg?.images?.[0]?.image_url?.url;

    if (!imageData) {
      console.error("No image in AI response. Full message keys:", JSON.stringify(Object.keys(msg || {})));
      if (msg?.content) {
        console.error("AI text response:", msg.content.substring(0, 200));
      }
      return new Response(
        JSON.stringify({ error: "No image generated by AI" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`Image data received, length: ${imageData.length}, prefix: ${imageData.substring(0, 30)}`);

    // Extract base64 data
    const base64Match = imageData.match(/^data:image\/(png|jpeg|jpg|webp);base64,(.+)$/);
    if (!base64Match) {
      console.error("Invalid image format, starts with:", imageData.substring(0, 50));
      return new Response(
        JSON.stringify({ error: "Invalid image data format" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const imageType = base64Match[1];
    const base64Data = base64Match[2];
    
    console.log(`Image type: ${imageType}, base64 length: ${base64Data.length}`);
    
    const binaryData = Uint8Array.from(atob(base64Data), (c) => c.charCodeAt(0));
    console.log(`Binary data size: ${binaryData.length} bytes`);

    // Reject tiny images (likely blank)
    if (binaryData.length < 5000) {
      console.error(`Image too small (${binaryData.length} bytes), likely blank`);
      return new Response(
        JSON.stringify({ error: "Generated image appears blank" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Better blank image detection: check multiple sections of the file
    // PNG/JPEG pixel data is in the middle/end of the file
    // A truly colorful image should have high entropy throughout
    const checkPoints = [
      Math.floor(binaryData.length * 0.25),
      Math.floor(binaryData.length * 0.5),
      Math.floor(binaryData.length * 0.75),
    ];
    
    let totalUnique = 0;
    for (const start of checkPoints) {
      const chunk = binaryData.slice(start, start + 500);
      const unique = new Set(chunk);
      totalUnique += unique.size;
    }
    const avgUnique = totalUnique / checkPoints.length;
    console.log(`Image entropy check: avg ${avgUnique.toFixed(0)} unique bytes per 500-byte chunk`);
    
    if (avgUnique < 10) {
      console.error(`Image has very low entropy (avg ${avgUnique}), likely blank`);
      return new Response(
        JSON.stringify({ error: "Generated image appears to be blank/solid color" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey);

    // Use random ID for filename (avoid Arabic chars)
    const randomId = crypto.randomUUID().replace(/-/g, "").slice(0, 12);
    const fileName = `${userId}/ai-icons/${randomId}.png`;
    console.log(`Uploading to: ${fileName}`);

    // Always upload as PNG for consistency
    const { error: uploadError } = await supabaseAdmin.storage
      .from("product-images")
      .upload(fileName, binaryData, {
        contentType: `image/${imageType}`,
        upsert: true,
      });

    if (uploadError) {
      console.error("Upload error:", uploadError);
      return new Response(
        JSON.stringify({ error: "Upload failed: " + uploadError.message }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const { data: publicUrlData } = supabaseAdmin.storage
      .from("product-images")
      .getPublicUrl(fileName);

    const iconUrl = publicUrlData.publicUrl;
    console.log(`Upload success! URL: ${iconUrl}`);

    // Upsert category_images record
    const { data: existing } = await supabaseAdmin
      .from("category_images")
      .select("id, image_url")
      .eq("user_id", userId)
      .eq("category", categoryName)
      .maybeSingle();

    if (existing) {
      // Delete old file from storage if it's an ai-icon
      if (existing.image_url?.includes("/ai-icons/")) {
        try {
          const oldPath = existing.image_url.split("/product-images/")[1];
          if (oldPath) {
            await supabaseAdmin.storage.from("product-images").remove([oldPath]);
            console.log(`Deleted old icon: ${oldPath}`);
          }
        } catch (e) {
          console.log("Could not delete old icon (non-critical):", e);
        }
      }

      const { error: updateError } = await supabaseAdmin
        .from("category_images")
        .update({ image_url: iconUrl })
        .eq("id", existing.id);
      
      if (updateError) {
        console.error("DB update error:", updateError);
      } else {
        console.log(`Updated record for "${categoryName}"`);
      }
    } else {
      const { error: insertError } = await supabaseAdmin
        .from("category_images")
        .insert({
          user_id: userId,
          category: categoryName,
          image_url: iconUrl,
        });
      
      if (insertError) {
        console.error("DB insert error:", insertError);
      } else {
        console.log(`Inserted record for "${categoryName}"`);
      }
    }

    return new Response(
      JSON.stringify({ iconUrl, success: true }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Error:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
