import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { categoryName, userId, iconStyle } = await req.json();
    console.log(`Generating icon for: "${categoryName}", style: ${iconStyle || "flat"}, user: ${userId}`);

    if (!categoryName || !userId) {
      return new Response(
        JSON.stringify({ error: "categoryName and userId are required" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      return new Response(
        JSON.stringify({ error: "LOVABLE_API_KEY is not configured" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const stylePrompts: Record<string, string> = {
      flat: "flat design icon, bold solid colors, clean geometric shapes, no gradients, minimal modern style, vibrant colors",
      "3d": "glossy 3D rendered icon, realistic lighting, soft shadows, depth and dimension, shiny surface",
      cartoon: "fun cartoon-style icon, thick black outlines, bright vibrant saturated colors, cute and playful design, expressive",
    };

    const styleDesc = stylePrompts[iconStyle || "flat"] || stylePrompts.flat;

    const prompt = `Generate a single colorful ${styleDesc} icon representing the food/drink category "${categoryName}". 
The icon should be a clear, recognizable food or drink illustration. 
Draw it on a clean light gray (#F0F0F0) background. 
Make the icon large, centered, and filling most of the image. 
Use rich, saturated colors to make the icon stand out. 
NO text, NO words, NO letters, NO numbers - ONLY the visual food/drink illustration.
The result must be a colorful, detailed icon - NOT a blank or empty image.`;

    console.log("Sending prompt to AI with model gemini-2.5-flash-image...");

    const aiResponse = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash-image",
        messages: [
          { 
            role: "user", 
            content: prompt 
          }
        ],
        modalities: ["image", "text"],
      }),
    });

    if (!aiResponse.ok) {
      const errorText = await aiResponse.text();
      console.error(`AI gateway error ${aiResponse.status}:`, errorText);
      if (aiResponse.status === 429) {
        return new Response(
          JSON.stringify({ error: "Rate limit exceeded, please try again later" }),
          { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (aiResponse.status === 402) {
        return new Response(
          JSON.stringify({ error: "Payment required for AI generation" }),
          { status: 402, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      return new Response(
        JSON.stringify({ error: "Failed to generate icon" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const aiData = await aiResponse.json();
    console.log("AI response received, checking for images...");
    
    const imageData = aiData.choices?.[0]?.message?.images?.[0]?.image_url?.url;

    if (!imageData) {
      console.error("No image in AI response. Response keys:", JSON.stringify(Object.keys(aiData.choices?.[0]?.message || {})));
      return new Response(
        JSON.stringify({ error: "No image generated by AI" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`Image data received, length: ${imageData.length}, starts with: ${imageData.substring(0, 30)}`);

    // Extract base64 data
    const base64Match = imageData.match(/^data:image\/(png|jpeg|jpg|webp);base64,(.+)$/);
    if (!base64Match) {
      console.error("Invalid image format, starts with:", imageData.substring(0, 50));
      return new Response(
        JSON.stringify({ error: "Invalid image data format" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const imageType = base64Match[1];
    const base64Data = base64Match[2];
    
    console.log(`Image type: ${imageType}, base64 length: ${base64Data.length}`);
    
    const binaryData = Uint8Array.from(atob(base64Data), (c) => c.charCodeAt(0));
    console.log(`Binary data size: ${binaryData.length} bytes`);

    // التحقق من أن الصورة ليست فارغة (أقل من 5KB تعني صورة فارغة على الأرجح)
    if (binaryData.length < 5000) {
      console.error(`Image too small (${binaryData.length} bytes), likely blank/empty`);
      return new Response(
        JSON.stringify({ error: "Generated image appears to be blank, please try again" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // فحص إضافي: التحقق من تنوع البيانات (صورة بيضاء بالكامل ستكون متشابهة)
    const sampleSize = Math.min(1000, binaryData.length);
    const sample = binaryData.slice(binaryData.length - sampleSize);
    const uniqueValues = new Set(sample);
    console.log(`Image diversity check: ${uniqueValues.size} unique byte values in last ${sampleSize} bytes`);
    
    if (uniqueValues.size < 5) {
      console.error(`Image has very low diversity (${uniqueValues.size} unique values), likely a solid color`);
      return new Response(
        JSON.stringify({ error: "Generated image appears to be a solid color, please try again" }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey);

    // Use random ID to avoid Arabic character issues in file names
    const randomId = crypto.randomUUID().replace(/-/g, "").slice(0, 12);
    const fileName = `${userId}/ai-icons/${randomId}.${imageType}`;
    console.log(`Uploading to: ${fileName}`);

    const { error: uploadError } = await supabaseAdmin.storage
      .from("product-images")
      .upload(fileName, binaryData, {
        contentType: `image/${imageType}`,
        upsert: true,
      });

    if (uploadError) {
      console.error("Upload error:", uploadError);
      return new Response(
        JSON.stringify({ error: "Failed to upload generated icon: " + uploadError.message }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const { data: publicUrlData } = supabaseAdmin.storage
      .from("product-images")
      .getPublicUrl(fileName);

    const iconUrl = publicUrlData.publicUrl;
    console.log(`Upload success! Public URL: ${iconUrl}`);

    // Check if category_images record exists
    const { data: existing } = await supabaseAdmin
      .from("category_images")
      .select("id")
      .eq("user_id", userId)
      .eq("category", categoryName)
      .maybeSingle();

    if (existing) {
      // Update existing record
      const { error: updateError } = await supabaseAdmin
        .from("category_images")
        .update({ image_url: iconUrl })
        .eq("id", existing.id);
      
      if (updateError) {
        console.error("DB update error:", updateError);
      } else {
        console.log(`Updated category_images record for "${categoryName}"`);
      }
    } else {
      // Insert new record
      const { error: insertError } = await supabaseAdmin
        .from("category_images")
        .insert({
          user_id: userId,
          category: categoryName,
          image_url: iconUrl,
        });
      
      if (insertError) {
        console.error("DB insert error:", insertError);
      } else {
        console.log(`Inserted new category_images record for "${categoryName}"`);
      }
    }

    return new Response(
      JSON.stringify({ iconUrl, success: true }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Error generating category icon:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
